#!/bin/bash
################################################################################
# CubeMX Code Integration Script
#
# This script integrates CubeMX generated code into the existing project
# structure while preserving USER CODE blocks and custom files.
#
# Usage: ./integrate_cubemx.sh
################################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Project directories
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORE_DIR="${PROJECT_DIR}/Core"
DRIVERS_DIR="${PROJECT_DIR}/Drivers"
SRC_DIR="${PROJECT_DIR}/src"
INCLUDE_DIR="${PROJECT_DIR}/include"
LIB_DIR="${PROJECT_DIR}/lib"
BACKUP_DIR="${PROJECT_DIR}/.backup/$(date +%Y%m%d_%H%M%S)"

# CubeMX generated files that need USER CODE merging
# All other files will be automatically preserved
CUBEMX_GENERATED_SOURCES=(
    "main.c"
    "stm32f1xx_it.c"
    "stm32f1xx_hal_msp.c"
    "system_stm32f1xx.c"
)

CUBEMX_GENERATED_HEADERS=(
    "main.h"
    "stm32f1xx_it.h"
    "stm32f1xx_hal_conf.h"
)

################################################################################
# Functions
################################################################################

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if a file is generated by CubeMX
is_cubemx_generated_source() {
    local filename="$1"
    for file in "${CUBEMX_GENERATED_SOURCES[@]}"; do
        if [ "$filename" = "$file" ]; then
            return 0
        fi
    done
    return 1
}

is_cubemx_generated_header() {
    local filename="$1"
    for file in "${CUBEMX_GENERATED_HEADERS[@]}"; do
        if [ "$filename" = "$file" ]; then
            return 0
        fi
    done
    return 1
}

# Check if required directories exist
check_directories() {
    log_info "Checking directories..."

    if [ ! -d "$CORE_DIR" ]; then
        log_error "Core/ directory not found. Please run CubeMX code generation first."
        exit 1
    fi

    if [ ! -d "$DRIVERS_DIR" ]; then
        log_error "Drivers/ directory not found. Please run CubeMX code generation first."
        exit 1
    fi

    log_info "✓ Core/ and Drivers/ directories found"
}

# Create backup of existing files
create_backup() {
    log_info "Creating backup at ${BACKUP_DIR}..."

    mkdir -p "$BACKUP_DIR"

    if [ -d "$SRC_DIR" ]; then
        cp -r "$SRC_DIR" "$BACKUP_DIR/"
        log_info "✓ Backed up src/"
    fi

    if [ -d "$INCLUDE_DIR" ]; then
        cp -r "$INCLUDE_DIR" "$BACKUP_DIR/"
        log_info "✓ Backed up include/"
    fi

    if [ -d "$LIB_DIR/Drivers" ]; then
        cp -r "$LIB_DIR/Drivers" "$BACKUP_DIR/"
        log_info "✓ Backed up lib/Drivers/"
    fi

    log_info "Backup created successfully"
}

# Extract USER CODE blocks from a file (content only, without BEGIN/END tags)
extract_user_code() {
    local file="$1"
    local temp_file="${file}.usercode"

    if [ ! -f "$file" ]; then
        return 1
    fi

    # Extract all USER CODE blocks (content only)
    awk '
        /\/\* USER CODE BEGIN/ {
            in_user_code = 1
            block_name = $0
            gsub(/.*USER CODE BEGIN /, "", block_name)
            gsub(/ \*\/.*/, "", block_name)
            print "###USER_CODE_BLOCK_START###" block_name
            next  # Skip the BEGIN line itself
        }
        /\/\* USER CODE END/ {
            in_user_code = 0
            print "###USER_CODE_BLOCK_END###"
            next  # Skip the END line itself
        }
        in_user_code { print }
    ' "$file" > "$temp_file"

    return 0
}

# Merge USER CODE blocks from old file into new file
merge_user_code() {
    local old_file="$1"
    local new_file="$2"
    local output_file="$3"

    if [ ! -f "$old_file" ]; then
        log_warn "Old file not found: $old_file, using new file as-is"
        cp "$new_file" "$output_file"
        return 0
    fi

    if [ ! -f "$new_file" ]; then
        log_error "New file not found: $new_file"
        return 1
    fi

    # Extract USER CODE from old file
    local usercode_file="${old_file}.usercode"
    extract_user_code "$old_file"

    if [ ! -f "$usercode_file" ]; then
        log_warn "No USER CODE blocks found in $old_file"
        cp "$new_file" "$output_file"
        return 0
    fi

    # Create a temporary Python script for merging
    local merge_script="${PROJECT_DIR}/.merge_temp.py"
    cat > "$merge_script" << 'PYTHON_EOF'
import sys
import re

def read_user_code_blocks(usercode_file):
    """Read USER CODE blocks from extracted file"""
    blocks = {}
    current_block = None
    current_content = []

    with open(usercode_file, 'r') as f:
        for line in f:
            if line.startswith('###USER_CODE_BLOCK_START###'):
                block_name = line.replace('###USER_CODE_BLOCK_START###', '').strip()
                current_block = block_name
                current_content = []
            elif line.startswith('###USER_CODE_BLOCK_END###'):
                if current_block:
                    # Join content exactly as extracted - preserve all newlines
                    content = ''.join(current_content)
                    blocks[current_block] = content
                current_block = None
            elif current_block is not None:
                current_content.append(line)

    return blocks

def merge_user_code(new_file, user_blocks, output_file):
    """Merge USER CODE blocks into new file"""
    with open(new_file, 'r') as f:
        content = f.read()

    # Replace each USER CODE block
    for block_name, block_content in user_blocks.items():
        # Pattern to match USER CODE BEGIN...END block
        # Capture the indentation before each tag, the tags themselves, and content between
        pattern = (
            r'([ \t]*)(/\* USER CODE BEGIN ' + re.escape(block_name) + r' \*/)'
            r'(.*?)'
            r'([ \t]*)(/\* USER CODE END ' + re.escape(block_name) + r' \*/)'
        )

        # Replace content between tags with extracted content
        # Use a replacer function to avoid interpreting backslashes in block_content
        # Preserve the indentation of both BEGIN and END tags
        def make_replacer(content_to_insert):
            def replacer(match):
                begin_indent = match.group(1)
                begin_tag = match.group(2)
                end_indent = match.group(4)
                end_tag = match.group(5)
                return begin_indent + begin_tag + '\n' + content_to_insert + end_indent + end_tag
            return replacer

        # Perform replacement
        new_content, count = re.subn(pattern, make_replacer(block_content), content, flags=re.DOTALL)
        if count == 0:
            print(f"Warning: Pattern not found for block '{block_name}'", file=sys.stderr)
        else:
            content = new_content

    with open(output_file, 'w') as f:
        f.write(content)

if __name__ == '__main__':
    if len(sys.argv) != 4:
        print("Usage: merge.py <usercode_file> <new_file> <output_file>")
        sys.exit(1)

    usercode_file = sys.argv[1]
    new_file = sys.argv[2]
    output_file = sys.argv[3]

    user_blocks = read_user_code_blocks(usercode_file)
    merge_user_code(new_file, user_blocks, output_file)
PYTHON_EOF

    # Run the merge script
    python3 "$merge_script" "$usercode_file" "$new_file" "$output_file"
    local result=$?

    # Cleanup
    rm -f "$merge_script" "$usercode_file"

    if [ $result -eq 0 ]; then
        log_info "✓ Merged USER CODE blocks in $(basename "$output_file")"
    else
        log_error "Failed to merge USER CODE blocks in $(basename "$output_file")"
        return 1
    fi

    return 0
}

# Process source files with USER CODE merging
process_source_files() {
    log_info "Processing source files..."

    mkdir -p "$SRC_DIR"

    # Process all files in Core/Src/
    if [ -d "${CORE_DIR}/Src" ]; then
        for new_file in "${CORE_DIR}/Src"/*.c; do
            if [ -f "$new_file" ]; then
                local filename=$(basename "$new_file")
                local old_file="${SRC_DIR}/${filename}"
                local temp_file="${SRC_DIR}/${filename}.merged"

                if is_cubemx_generated_source "$filename"; then
                    # CubeMX generated file - merge USER CODE blocks
                    log_info "Processing $filename (CubeMX generated)..."
                    merge_user_code "$old_file" "$new_file" "$temp_file"
                    mv "$temp_file" "$old_file"
                else
                    # Custom file - preserve if it exists, otherwise copy new one
                    if [ ! -f "$old_file" ]; then
                        log_info "Copying new custom file: $filename"
                        cp "$new_file" "$old_file"
                    else
                        log_info "✓ Preserving custom file: $filename"
                    fi
                fi
            fi
        done
    fi
}

# Process header files with USER CODE merging
process_header_files() {
    log_info "Processing header files..."

    mkdir -p "$INCLUDE_DIR"

    # Process all files in Core/Inc/
    if [ -d "${CORE_DIR}/Inc" ]; then
        for new_file in "${CORE_DIR}/Inc"/*.h; do
            if [ -f "$new_file" ]; then
                local filename=$(basename "$new_file")
                local old_file="${INCLUDE_DIR}/${filename}"
                local temp_file="${INCLUDE_DIR}/${filename}.merged"

                if is_cubemx_generated_header "$filename"; then
                    # CubeMX generated file - merge USER CODE blocks
                    log_info "Processing $filename (CubeMX generated)..."
                    merge_user_code "$old_file" "$new_file" "$temp_file"
                    mv "$temp_file" "$old_file"
                else
                    # Custom file - preserve if it exists, otherwise copy new one
                    if [ ! -f "$old_file" ]; then
                        log_info "Copying new custom file: $filename"
                        cp "$new_file" "$old_file"
                    else
                        log_info "✓ Preserving custom file: $filename"
                    fi
                fi
            fi
        done
    fi
}

# Move Drivers directory
process_drivers() {
    log_info "Processing Drivers..."

    mkdir -p "$LIB_DIR"

    if [ -d "$DRIVERS_DIR" ]; then
        # Remove old Drivers if exists
        if [ -d "$LIB_DIR/Drivers" ]; then
            log_info "Removing old lib/Drivers..."
            rm -rf "$LIB_DIR/Drivers"
        fi

        # Move new Drivers
        mv "$DRIVERS_DIR" "$LIB_DIR/"
        log_info "✓ Moved Drivers/ to lib/Drivers/"
    fi
}

# Cleanup generated directories
cleanup_generated() {
    log_info "Cleaning up generated directories..."

    if [ -d "$CORE_DIR" ]; then
        rm -rf "$CORE_DIR"
        log_info "✓ Removed Core/"
    fi

    # Remove any leftover .usercode files
    find "$SRC_DIR" "$INCLUDE_DIR" -name "*.usercode" -delete 2>/dev/null || true
    find "$SRC_DIR" "$INCLUDE_DIR" -name "*.merged" -delete 2>/dev/null || true
}

# Display summary
display_summary() {
    echo ""
    log_info "================================"
    log_info "Integration completed successfully!"
    log_info "================================"
    echo ""
    log_info "Backup location: $BACKUP_DIR"
    log_info "Next steps:"
    echo "  1. Review the changes with: git diff"
    echo "  2. Build the project"
    echo "  3. If everything works, commit the changes"
    echo "  4. If there are issues, restore from backup: cp -r $BACKUP_DIR/src/* src/ && cp -r $BACKUP_DIR/include/* include/"
    echo ""
}

################################################################################
# Main execution
################################################################################

main() {
    log_info "Starting CubeMX code integration..."
    echo ""

    check_directories
    create_backup
    process_source_files
    process_header_files
    process_drivers
    cleanup_generated
    display_summary
}

# Run main function
main
